CREATE TABLE IF NOT EXISTS `players` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(24) NOT NULL,
  `registered` int(11) NOT NULL DEFAULT '0',
  `password` char(64) NOT NULL,
  `salt` char(16) NOT NULL,
  `email` varchar(50) DEFAULT NULL,
  `admin` int(11) NOT NULL DEFAULT '0',
  `skin` int(11) NOT NULL DEFAULT '0',
  `chargender` int(11) NOT NULL DEFAULT '0',
  `fightstyle` int(11) NOT NULL DEFAULT '4',
  `money` int(20) NOT NULL DEFAULT '0',
  `bankmoney` int(20) NOT NULL DEFAULT '0',
  `kills` mediumint(8) NOT NULL DEFAULT '0',
  `deaths` mediumint(8) NOT NULL DEFAULT '0',
  `x` float NOT NULL DEFAULT '0',
  `y` float NOT NULL DEFAULT '0',
  `z` float NOT NULL DEFAULT '0',
  `angle` float NOT NULL DEFAULT '0',
  `interior` tinyint(3) NOT NULL DEFAULT '0',
  `virtualworld` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
);